import {Inter} from "next/font/google";
import {Footer} from "@/components/Footer";
import {Navigation} from "../components/Navigation";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="h-screen flex flex-col ">
					<Navigation />
					<main className="flex-grow">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
